[project]
name = "network-analyser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "comtypes>=1.4.12",
    "dnspython>=2.8.0",
    "pywifi>=1.1.12",
    "scapy>=2.6.1",
]
